Add new functions + tests
py1sl/neutron_tools pull request #15
Opened 2022-01-12 17:01 UTC by jacktweddle

Added functions and tests for:

- minimum distance between a point and a plane
- central co-ords and radius of the circle when a plane intercepts a sphere
- equation of the line where two planes intersect
- point of intersection between a line segment and a plane
- rotation of a set of points about the x, y and z Cartesian axes
- translation of a point by a 3D vector
- converting between Cartesian, CPC and SPC coordinate systems

2022-01-13 09:28 UTC, py1sl requested changes
generally looks good, few minor changes to make.  testing could be expanded, 
nice use of np.testing for arrays, I've not tried that before

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +        t = t = plane[3] - np.dot(p0, plane[:3]) / np.dot(p1-p0, plane[:3])
t = t =  
tidy up

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    print(p, '+ t * ', n)
remove or change to logging

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    for i in range(len(point_list)):
probably more pythonic to use 
```
for i, point in enumerate(point_list):
    new_point_list[i] = np.dot(R, (point.T - o.T))'
```

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    for i in range(len(point_list)):
as above

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    for i in range(len(point_list)):
as above

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    for i in range(len(point_list)):
as above

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    z_cyl = z
remove, just return z

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    elif x < 0:
can just be else

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    elif x < 0:
can just be else

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    x = rho*np.cos(phi)
pep8 spaces needed around operators

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    z = r*np.cos(theta)
pep8 spaces needed around operators

2022-01-13 09:28 UTC, py1sl commented on geom_utils.py
> +    z_cyl = r*np.cos(theta)
pep8 spaces needed around operators

2022-01-13 09:28 UTC, py1sl commented on tests/test_geom_util.py
> +    def test_cylindrical_to_cartesian(self):
should also test the error condition

2022-01-13 09:28 UTC, py1sl commented on tests/test_geom_util.py
> +    def test_cylindrical_to_spherical(self):
should also test the error condition

2022-01-13 09:28 UTC, py1sl commented on tests/test_geom_util.py
> +    def test_spherical_to_cartesian(self):
should also test the error condition

2022-01-13 09:28 UTC, py1sl commented on tests/test_geom_util.py
> +    def test_spherical_to_cylindrical(self):
should also test the error condition

2022-01-13 10:11 UTC, jacktweddle commented
All the requested changes have been made, I think it automatically updates here?

2022-01-14 08:27 UTC, py1sl approved these changes

2022-01-18 11:25 UTC, jacktweddle commented
Hi Steve,

I've updated all the functions to use numpy arrays and have added new tests that have improved the coverage to 98%. Couldn't quite get 100% because of a few logging cases :(

Hopefully all is good!

2022-01-19 12:22 UTC, jacktweddle commented
pep8 issues have now been cleared up :)

2022-01-19 21:00 UTC, merged